<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE Major_Sport_Venues_Usage[
    <!ELEMENT Major_Sport_Venues_Usage (VENUEID)>
    <!ELEMENT VENUEID ( USE, USE_POP, TEAM, LEAGUE, CONFERENCE, DIVISION, INST_AFFIL, TRACK_TYPE, LENGTH_MI, ROOF_TYPE)>

    <!ELEMENT VENUEID (#PCDATA)>
    <!ELEMENT USE (#PCDATA)>
    <!ELEMENT USE_POP (#PCDATA)>
    <!ELEMENT TEAM (#PCDATA)>
    <!ELEMENT LEAGUE (#PCDATA)>
    <!ELEMENT CONFERENCE (#PCDATA)>
    <!ELEMENT DIVISION (#PCDATA)>
    <!ELEMENT INST_AFFIL (#PCDATA)>
    <!ELEMENT TRACK_TYPE (#PCDATA)>
    <!ELEMENT LENGTH_MI (#PCDATA)>
    <!ELEMENT ROOF_TYPE (#PCDATA)>

    <!ATTLIST VENUEID id CDATA #REQUIRED>
]>
<Major_Sport_Venues_Usage>
    <VENUEID id="1">
        <USE> IRL </USE>
        <USE_POP> 45000 </USE_POP>
        <TEAM> NOT APPLICABLE </TEAM>
        <LEAGUE> NOT APPLICABLE </LEAGUE>
        <CONFERENCE> NOT APPLICABLE </CONFERENCE>
        <DIVISION> NOT APPLICABLE </DIVISION>
        <INST_AFFIL> NOT APPLICABLE </INST_AFFIL>
        <TRACK_TYPE> TRI-OVAL </TRACK_TYPE>
        <LENGTH_MI> 1 </LENGTH_MI>
        <ROOF_TYPE> NOT APPLICABLE </ROOF_TYPE>
    </VENUEID>
    
   <VENUEID id="385">
        <USE> IRL </USE>
        <USE_POP> 257325 </USE_POP>
        <TEAM> NOT APPLICABLE </TEAM>
        <LEAGUE> NOT APPLICABLE </LEAGUE>
        <CONFERENCE> NOT APPLICABLE </CONFERENCE>
        <DIVISION> NOT APPLICABLE </DIVISION>
        <INST_AFFIL> NOT APPLICABLE </INST_AFFIL>
        <TRACK_TYPE> RECTANGULAR OVAL </TRACK_TYPE>
        <LENGTH_MI> 2.5 </LENGTH_MI>
        <ROOF_TYPE> NOT APPLICABLE </ROOF_TYPE>
    </VENUEID>

    <VENUEID id="378">
        <USE> IRL </USE>
        <USE_POP> 68000 </USE_POP>
        <TEAM> NOT APPLICABLE </TEAM>
        <LEAGUE> NOT APPLICABLE </LEAGUE>
        <CONFERENCE> NOT APPLICABLE </CONFERENCE>
        <DIVISION> NOT APPLICABLE </DIVISION>
        <INST_AFFIL> NOT APPLICABLE </INST_AFFIL>
        <TRACK_TYPE> D-SHAPED OVAL </TRACK_TYPE>
        <LENGTH_MI> 2 </LENGTH_MI>
        <ROOF_TYPE> NOT APPLICABLE </ROOF_TYPE>
    </VENUEID>
    
    <VENUEID id="386">
        <USE> IRL </USE>
        <USE_POP> 47000 </USE_POP>
        <TEAM> NOT APPLICABLE </TEAM>
        <LEAGUE> NOT APPLICABLE </LEAGUE>
        <CONFERENCE> NOT APPLICABLE </CONFERENCE>
        <DIVISION> NOT APPLICABLE </DIVISION>
        <INST_AFFIL> NOT APPLICABLE </INST_AFFIL>
        <TRACK_TYPE> ROAD COURSE </TRACK_TYPE>
        <LENGTH_MI> 2.5 </LENGTH_MI>
        <ROOF_TYPE> NOT APPLICABLE </ROOF_TYPE>
    </VENUEID>

    <VENUEID id="406">
        <USE> IRL </USE>
        <USE_POP> 191122 </USE_POP>
        <TEAM> NOT APPLICABLE </TEAM>
        <LEAGUE> NOT APPLICABLE </LEAGUE>
        <CONFERENCE> NOT APPLICABLE </CONFERENCE>
        <DIVISION> NOT APPLICABLE </DIVISION>
        <INST_AFFIL> NOT APPLICABLE </INST_AFFIL>
        <TRACK_TYPE> QUAD-OVAL </TRACK_TYPE>
        <LENGTH_MI> 1.5 </LENGTH_MI>
        <ROOF_TYPE> NOT APPLICABLE </ROOF_TYPE>
    </VENUEID>

    <VENUEID id="16">
        <USE> IRL </USE>
        <USE_POP> </USE_POP>
        <TEAM> NOT APPLICABLE </TEAM>
        <LEAGUE> NOT APPLICABLE </LEAGUE>
        <CONFERENCE> NOT APPLICABLE </CONFERENCE>
        <DIVISION> NOT APPLICABLE </DIVISION>
        <INST_AFFIL> NOT APPLICABLE </INST_AFFIL>
        <TRACK_TYPE> STREET </TRACK_TYPE>
        <LENGTH_MI> 1.8 </LENGTH_MI>
        <ROOF_TYPE> NOT APPLICABLE </ROOF_TYPE>
    </VENUEID>

    <VENUEID id="17">
        <USE> IRL </USE>
        <USE_POP> 191122 </USE_POP>
        <TEAM> NOT APPLICABLE </TEAM>
        <LEAGUE> NOT APPLICABLE </LEAGUE>
        <CONFERENCE> NOT APPLICABLE </CONFERENCE>
        <DIVISION> NOT APPLICABLE </DIVISION>
        <INST_AFFIL> NOT APPLICABLE </INST_AFFIL>
        <TRACK_TYPE> STREET </TRACK_TYPE>
        <LENGTH_MI> 1.968 </LENGTH_MI>
        <ROOF_TYPE> NOT APPLICABLE </ROOF_TYPE>
    </VENUEID>

   <VENUEID id="18">
        <USE> IRL </USE>
        <USE_POP> </USE_POP>
        <TEAM> NOT APPLICABLE </TEAM>
        <LEAGUE> NOT APPLICABLE </LEAGUE>
        <CONFERENCE> NOT APPLICABLE </CONFERENCE>
        <DIVISION> NOT APPLICABLE </DIVISION>
        <INST_AFFIL> NOT APPLICABLE </INST_AFFIL>
        <TRACK_TYPE> ROAD COUSE </TRACK_TYPE>
        <LENGTH_MI> 2.83 </LENGTH_MI>
        <ROOF_TYPE> NOT APPLICABLE </ROOF_TYPE>
    </VENUEID>

    <VENUEID id="387">
        <USE> IRL </USE>
        <USE_POP> 30000</USE_POP>
        <TEAM> NOT APPLICABLE </TEAM>
        <LEAGUE> NOT APPLICABLE </LEAGUE>
        <CONFERENCE> NOT APPLICABLE </CONFERENCE>
        <DIVISION> NOT APPLICABLE </DIVISION>
        <INST_AFFIL> NOT APPLICABLE </INST_AFFIL>
        <TRACK_TYPE> D-SHAPED OVAL </TRACK_TYPE>
        <LENGTH_MI> 0.8 </LENGTH_MI>
        <ROOF_TYPE> NOT APPLICABLE </ROOF_TYPE>
    </VENUEID>

    <VENUEID id="20">
        <USE> IRL </USE>
        <USE_POP> 30000</USE_POP>
        <TEAM> NOT APPLICABLE </TEAM>
        <LEAGUE> NOT APPLICABLE </LEAGUE>
        <CONFERENCE> NOT APPLICABLE </CONFERENCE>
        <DIVISION> NOT APPLICABLE </DIVISION>
        <INST_AFFIL> NOT APPLICABLE </INST_AFFIL>
        <TRACK_TYPE> STREET </TRACK_TYPE>
        <LENGTH_MI> 1.75 </LENGTH_MI>
        <ROOF_TYPE> NOT APPLICABLE </ROOF_TYPE>
    </VENUEID>

</Major_Sport_Venues_Usage>